In [2]:
import requests
import pandas as pd

# API URL
url = "https://founda.boors365.ir/api/v1/tickers?force_refresh=false&max_concurrent=20"

# Send GET request to the API
response = requests.get(url)

# Check for successful response
if response.status_code == 200:
    data = response.json()
    
    # Extract 'name' from each item in 'data'
    company_names = [item['full_name'] for item in data.get('data', [])]
    tickers =[item['name'] for item in data.get('data',[])]
    # Create a DataFrame
    df = pd.DataFrame({
        'ticker': tickers,
        'company_name': company_names
    })

In [3]:
df

     ticker                         company_name
0     بنیرو                           نیرو ترانس
1      فخاس                          فولادخراسان
2     زشریف                 کشت و صنعت شریف آباد
3    کفرآور    فرآورده های سیمان شرق (سهامی عام)
4      سرود                         سیمان شاهرود
..      ...                                  ...
899    رتاپ  تجارت الکترونیک پارسیان (سهامی خاص)
900  خمحرکه                     صنعتی نیرو محرکه
901  انتخاب               انتخاب الکترونیک آرمان
902    خفنر                        فنر سازی خاور
903  پرداخت                        به پرداخت ملت

[904 rows x 2 columns]

In [6]:
df_codal=pd.read_csv('../output/companies_cleaned.csv')

In [7]:
df_codal=df_codal[['ticker','name']]

In [8]:
missing_in_df = df_codal[~df_codal['ticker'].isin(df['ticker'])]
print(f"{len(missing_in_df)} tickers are in df_codal but not in df.")
display(missing_in_df)
missing_in_df.to_excel('missing_in_boors365_exist_in_codal.xlsx',index=False)

4445 tickers are in df_codal but not in df.

,ticker,name
0,آذرنگین,آذر نگین
1,بنیاد تعاون نیروی انتظامی جمهوری اسلامی ایران,بنیاد تعاون نیروی انتظامی جمهوری اسلامی ایران
2,بین المللی خدمات مسافرت هوایی ایرانگردی و جها...,بین المللی خدمات مسافرت هوایی ایرانگردی و جهان...
3,پترونیک,مهندسی پترونیک صنعت
4,توس پیوند,توس پیوند
...,...,...
5295,کیمیاورزان مهر غرب,کیمیا ورزان مهر غرب
5296,کیمیای پارس خاور میانه,کیمیای پارس خاور میانه
5297,کیمیایی غرب گستر,صنایع کیمیای غرب گستر
5298,کیهان دریا ایمن قشم,کیهان دریا ایمن قشم
5299,کک طبس,کک طبس

In [39]:
df[~df['ticker'].isin(df_codal['ticker'])].to_excel('useless_companies.xlsx',index=False)

In [9]:
all_included = df['ticker'].isin(df_codal['name']).all()
print("✅ All tickers in df exist in df_codal" if all_included else "❌ Some tickers in df are missing in df_codal")

❌ Some tickers in df are missing in df_codal